#ifndef COMMONDEFINES_H
#define COMMONDEFINES_H

#define ARGUMENT_HELP_STRING "help"
#define ARGUMENT_HELP_LIST ARGUMENT_HELP_STRING " h usage ?"
#define ARGUMENT_INPUTIMAGE_STRING "img"
#define ARGUMENT_INPUTIMAGE_LIST ARGUMENT_INPUTIMAGE_STRING " input"

#define INPUTIMAGE_WINDOW "OriginalImage"
#define OUTPUTIMAGE_WINDOW "SuperpixelImage"

#define THRESHHOLD_MAX_VALUE 20

#define OUTPUTIMAGE_NAME "outputImage.jpg"
#define OUTPUTIMAGE_PATH "../Bilder/" OUTPUTIMAGE_NAME

#endif // COMMONDEFINES_H