#ifndef COMMONDEFINES_H
#define COMMONDEFINES_H

#define ARGUMENT_HELP_STRING "help"
#define ARGUMENT_HELP_LIST ARGUMENT_HELP_STRING " h usage ?"
#define ARGUMENT_INPUTIMAGE_STRING "img"
#define ARGUMENT_INPUTIMAGE_LIST ARGUMENT_INPUTIMAGE_STRING " input"

#endif // COMMONDEFINES_H